
export const JYOTISH_DATA = {
    tithis: [
        { id: 1, name: { ru: "Пратипад", en: "Pratipada", he: "פרטיפדה" }, type: { ru: "Нанда (Радость)", en: "Nanda (Joy)", he: "ננדה (שמחה)" }, description: { ru: "Планирование, начало строительства", en: "Planning, start of construction", he: "תכנון, תחילת בנייה" } },
        { id: 2, name: { ru: "Двития", en: "Dwitiya", he: "דוויטיה" }, type: { ru: "Бхадра (Мудрость)", en: "Bhadra (Wisdom)", he: "בהדרה (חוכמה)" }, description: { ru: "Закладка фундамента, творчество", en: "Foundation laying, creativity", he: "יסודות, יצירתיות" } },
        { id: 3, name: { ru: "Трития", en: "Tritiya", he: "טריטיה" }, type: { ru: "Джая (Победа)", en: "Jaya (Victory)", he: "ג'איה (ניצחון)" }, description: { ru: "Стрижка, вступление в должность", en: "Haircut, taking office", he: "תספורת, כניסה לתפקיד" } },
        { id: 4, name: { ru: "Чатуртхи", en: "Chaturthi", he: "צ'טורתי" }, type: { ru: "Рикта (Пустые руки)", en: "Rikta (Empty Hands)", he: "ריקתה (ידיים ריקות)" }, description: { ru: "Уборка, избавление от ненужного", en: "Cleaning, getting rid of unnecessary", he: "ניקיון, סילוק מיותר" } },
        { id: 5, name: { ru: "Панчами", en: "Panchami", he: "פנצ'מי" }, type: { ru: "Пурна (Полнота)", en: "Purna (Fullness)", he: "פורנה (מלאות)" }, description: { ru: "Лечение, обучение, духовные практики", en: "Healing, learning, spiritual practices", he: "ריפוי, למידה, פרקטיקות רוחניות" } },
        { id: 6, name: { ru: "Шаштхи", en: "Shashthi", he: "ששתי" }, type: { ru: "Нанда (Радость)", en: "Nanda (Joy)", he: "ננדה (שמחה)" }, description: { ru: "Встречи, новые знакомства", en: "Meetings, new acquaintances", he: "פגישות, היכרויות חדשות" } },
        { id: 7, name: { ru: "Саптами", en: "Saptami", he: "ספטמי" }, type: { ru: "Бхадра (Мудрость)", en: "Bhadra (Wisdom)", he: "בהדרה (חוכמה)" }, description: { ru: "Покупки, путешествия", en: "Shopping, travel", he: "קניות, נסיעות" } },
        { id: 8, name: { ru: "Аштами", en: "Ashtami", he: "אשטמי" }, type: { ru: "Джая (Победа)", en: "Jaya (Victory)", he: "ג'איה (ניצחון)" }, description: { ru: "Танцы, искусство, споры", en: "Dancing, art, disputes", he: "ריקודים, אומנות, ויכוחים" } },
        { id: 9, name: { ru: "Навами", en: "Navami", he: "נבאמי" }, type: { ru: "Рикта (Пустые руки)", en: "Rikta (Empty Hands)", he: "ריקתה (ידיים ריקות)" }, description: { ru: "Физическая работа, конкуренция", en: "Physical work, competition", he: "עבודה פיזית, תחרות" } },
        { id: 10, name: { ru: "Дашами", en: "Dashami", he: "דשאמי" }, type: { ru: "Пурна (Полнота)", en: "Purna (Fullness)", he: "פורנה (מלאות)" }, description: { ru: "Свадьба, начало важных дел", en: "Wedding, starting important tasks", he: "חתונה, התחלת משימות חשובות" } },
        { id: 11, name: { ru: "Экадаши", en: "Ekadashi", he: "אקדשי" }, type: { ru: "Нанда (Радость)", en: "Nanda (Joy)", he: "ננדה (שמחה)" }, description: { ru: "Пост, медитация", en: "Fasting, meditation", he: "צום, מדיטציה" } },
        { id: 12, name: { ru: "Двадаши", en: "Dwadashi", he: "דבדשי" }, type: { ru: "Бхадра (Мудрость)", en: "Bhadra (Wisdom)", he: "בהדרה (חוכמה)" }, description: { ru: "Благотворительность, обряды", en: "Charity, rituals", he: "צדקה, טקסים" } },
        { id: 13, name: { ru: "Трайодаши", en: "Trayodashi", he: "טריודשי" }, type: { ru: "Джая (Победа)", en: "Jaya (Victory)", he: "ג'איה (ניצחון)" }, description: { ru: "Очищение, общение", en: "Purification, socializing", he: "טיהור, חברות" } },
        { id: 14, name: { ru: "Чатурдаши", en: "Chaturdashi", he: "צ'טורדשי" }, type: { ru: "Рикта (Пустые руки)", en: "Rikta (Empty Hands)", he: "ריקתה (ידיים ריקות)" }, description: { ru: "Чтение мантр, защита", en: "Chanting mantras, protection", he: "מנטרות, הגנה" } },
        { id: 15, name: { ru: "Пурнима (Полнолуние)", en: "Purnima", he: "פורנימה" }, type: { ru: "Пурна (Полнота)", en: "Purna (Fullness)", he: "פורנה (מלאות)" }, description: { ru: "Празднование, духовность", en: "Celebration, spirituality", he: "חגיגה, רוחניות" } },
        { id: 30, name: { ru: "Амавасья (Новолуние)", en: "Amavasya", he: "אמווסיה" }, type: { ru: "Питри (Предки)", en: "Pitri (Ancestors)", he: "פיטרי (אבות)" }, description: { ru: "Почитание предков, тайна", en: "Honoring ancestors, mystery", he: "כיבוד אבות, מסתורין" } }
    ],
    nakshatras: [
        { id: 1, name: { ru: "Ашвини", en: "Ashwini", he: "אשוויני" }, ruler: { ru: "Кету", en: "Ketu", he: "קאטו" }, deity: { ru: "Ашвини Кумары", en: "Ashwini Kumaras", he: "אשוויני קומארס" } },
        { id: 2, name: { ru: "Бхарани", en: "Bharani", he: "בהראני" }, ruler: { ru: "Венера", en: "Venus", he: "נוגה" }, deity: { ru: "Яма", en: "Yama", he: "יאמה" } },
        { id: 3, name: { ru: "Криттика", en: "Krittika", he: "קריטיקה" }, ruler: { ru: "Солнце", en: "Sun", he: "שמש" }, deity: { ru: "Агни", en: "Agni", he: "אגני" } },
        { id: 4, name: { ru: "Рохини", en: "Rohini", he: "רוהיני" }, ruler: { ru: "Луна", en: "Moon", he: "ירח" }, deity: { ru: "Брахма", en: "Brahma", he: "ברהמה" } },
        { id: 5, name: { ru: "Мригашира", en: "Mrigashira", he: "מריגשירא" }, ruler: { ru: "Марс", en: "Mars", he: "מאדים" }, deity: { ru: "Сома", en: "Soma", he: "סומה" } },
        { id: 6, name: { ru: "Ардра", en: "Ardra", he: "ארדרה" }, ruler: { ru: "Раху", en: "Rahu", he: "ראהו" }, deity: { ru: "Рудра", en: "Rudra", he: "רודרה" } },
        { id: 7, name: { ru: "Пунарвасу", en: "Punarvasu", he: "פונרבסו" }, ruler: { ru: "Юпитер", en: "Jupiter", he: "צדק" }, deity: { ru: "Адити", en: "Aditi", he: "אדיטי" } },
        { id: 8, name: { ru: "Пушья", en: "Pushya", he: "פושיה" }, ruler: { ru: "Сатурн", en: "Saturn", he: "שבתאי" }, deity: { ru: "Брихаспати", en: "Brihaspati", he: "בריהספטי" } },
        { id: 9, name: { ru: "Ашлеша", en: "Ashlesha", he: "אשלשה" }, ruler: { ru: "Меркурий", en: "Mercury", he: "חמה" }, deity: { ru: "Наги", en: "Nagas", he: "נאגות" } },
        { id: 10, name: { ru: "Магха", en: "Magha", he: "מאגהה" }, ruler: { ru: "Кету", en: "Ketu", he: "קאטו" }, deity: { ru: "Питри", en: "Pitri", he: "פיטרי" } },
        { id: 11, name: { ru: "Пурва Пхалгуни", en: "Purva Phalguni", he: "פורבה פלגוני" }, ruler: { ru: "Венера", en: "Venus", he: "נוגה" }, deity: { ru: "Бхага", en: "Bhaga", he: "בהאגה" } },
        { id: 12, name: { ru: "Уттара Пхалгуни", en: "Uttara Phalguni", he: "אוטרה פלגוני" }, ruler: { ru: "Солнце", en: "Sun", he: "שמש" }, deity: { ru: "Арьяман", en: "Aryaman", he: "ארימן" } },
        { id: 13, name: { ru: "Хаста", en: "Hasta", he: "האסטה" }, ruler: { ru: "Луна", en: "Moon", he: "ירח" }, deity: { ru: "Савитар", en: "Savitar", he: "סביטר" } },
        { id: 14, name: { ru: "Читра", en: "Chitra", he: "צ'יטרה" }, ruler: { ru: "Марс", en: "Mars", he: "מאדים" }, deity: { ru: "Вишвакарма", en: "Vishwakarma", he: "וישווקרמה" } },
        { id: 15, name: { ru: "Свати", en: "Swati", he: "סוואטי" }, ruler: { ru: "Раху", en: "Rahu", he: "ראהו" }, deity: { ru: "Вайю", en: "Vayu", he: "ואיו" } },
        { id: 16, name: { ru: "Вишакха", en: "Vishakha", he: "וישאקה" }, ruler: { ru: "Юпитер", en: "Jupiter", he: "צדק" }, deity: { ru: "Индра-Агни", en: "Indra-Agni", he: "אינדרה-אגני" } },
        { id: 17, name: { ru: "Анурадха", en: "Anuradha", he: "אנורדהה" }, ruler: { ru: "Сатурн", en: "Saturn", he: "שבתאי" }, deity: { ru: "Митра", en: "Mitra", he: "מיטרה" } },
        { id: 18, name: { ru: "Джиештха", en: "Jyeshtha", he: "ג'יישטה" }, ruler: { ru: "Меркурий", en: "Mercury", he: "חמה" }, deity: { ru: "Индра", en: "Indra", he: "אינדרה" } },
        { id: 19, name: { ru: "Мула", en: "Mula", he: "מולה" }, ruler: { ru: "Кету", en: "Ketu", he: "קאטו" }, deity: { ru: "Ниррити", en: "Nirriti", he: "ניריטי" } },
        { id: 20, name: { ru: "Пурва Ашадха", en: "Purva Ashadha", he: "פורבה אשדה" }, ruler: { ru: "Венера", en: "Venus", he: "נוגה" }, deity: { ru: "Апас", en: "Apas", he: "אפאס" } },
        { id: 21, name: { ru: "Уттара Ашадха", en: "Uttara Ashadha", he: "אוטרה אשדה" }, ruler: { ru: "Солнце", en: "Sun", he: "שמש" }, deity: { ru: "Вишведевы", en: "Vishvedevas", he: "וישוודווס" } },
        { id: 22, name: { ru: "Шравана", en: "Shravana", he: "שראוונה" }, ruler: { ru: "Луна", en: "Moon", he: "ירח" }, deity: { ru: "Вишну", en: "Vishnu", he: "וישנו" } },
        { id: 23, name: { ru: "Дхаништха", en: "Dhanishtha", he: "דהנישטה" }, ruler: { ru: "Марс", en: "Mars", he: "מאדים" }, deity: { ru: "Васу", en: "Vasu", he: "ואסו" } },
        { id: 24, name: { ru: "Шатабхиша", en: "Shatabhisha", he: "שטאבהישה" }, ruler: { ru: "Раху", en: "Rahu", he: "ראהו" }, deity: { ru: "Варуна", en: "Varuna", he: "וארונה" } },
        { id: 25, name: { ru: "Пурва Бхадрапада", en: "Purva Bhadrapada", he: "פורבה בהדרפדה" }, ruler: { ru: "Юпитер", en: "Jupiter", he: "צדק" }, deity: { ru: "Аджа Экапада", en: "Aja Ekapada", he: "אג'ה אקפדה" } },
        { id: 26, name: { ru: "Уттара Бхадрапада", en: "Uttara Bhadrapada", he: "אוטרה בהדרפדה" }, ruler: { ru: "Сатурн", en: "Saturn", he: "שבתאי" }, deity: { ru: "Ахир Будхнья", en: "Ahir Budhnya", he: "אהיר בודניה" } },
        { id: 27, name: { ru: "Ревати", en: "Revati", he: "רבאטי" }, ruler: { ru: "Меркурий", en: "Mercury", he: "חמה" }, deity: { ru: "Пушан", en: "Pushan", he: "פושן" } }
    ],
    yogas: [
        { ru: "Вишкумбха", en: "Vishkumbha", he: "וישקומבה" },
        { ru: "Прити", en: "Priti", he: "פריטי" },
        { ru: "Аюшман", en: "Ayushman", he: "איושמן" },
        { ru: "Саубхагья", en: "Saubhagya", he: "סאובהגיה" },
        { ru: "Шобхана", en: "Shobhana", he: "שובהנה" },
        { ru: "Атиганда", en: "Atiganda", he: "אטיגנדה" },
        { ru: "Сукарма", en: "Sukarma", he: "סוקרמה" },
        { ru: "Дхрити", en: "Dhriti", he: "דהריטי" },
        { ru: "Шула", en: "Shula", he: "שולה" },
        { ru: "Ганда", en: "Ganda", he: "גנדה" },
        { ru: "Вриддхи", en: "Vriddhi", he: "ורידהי" },
        { ru: "Дхрува", en: "Dhruva", he: "דהרובה" },
        { ru: "Вьягхата", en: "Vyaghata", he: "ויאגהטה" },
        { ru: "Харшана", en: "Harshana", he: "הרשנה" },
        { ru: "Ваджра", en: "Vajra", he: "ווג'רה" },
        { ru: "Сиддхи", en: "Siddhi", he: "סידהי" },
        { ru: "Вьятипата", en: "Vyatipata", he: "ויאטיפטה" },
        { ru: "Вариян", en: "Variyan", he: "ואריאן" },
        { ru: "Паригха", en: "Parigha", he: "פריגה" },
        { ru: "Шива", en: "Shiva", he: "שיווה" },
        { ru: "Сиддха", en: "Siddha", he: "סידהה" },
        { ru: "Садхья", en: "Sadhya", he: "סאדיה" },
        { ru: "Шубха", en: "Shubha", he: "שובהה" },
        { ru: "Шукла", en: "Shukla", he: "שוקלה" },
        { ru: "Брахма", en: "Brahma", he: "ברהמה" },
        { ru: "Индра", en: "Indra", he: "אינדרה" },
        { ru: "Вайдхрити", en: "Vaidhriti", he: "ויידהריטי" }
    ],
    karanas: [
        { ru: "Бава", en: "Bava", he: "באווה" },
        { ru: "Балава", en: "Balava", he: "בלאווה" },
        { ru: "Каулава", en: "Kaulava", he: "קאולווה" },
        { ru: "Тнайтила", en: "Taitila", he: "טאיטילה" },
        { ru: "Гара", en: "Gara", he: "גארה" },
        { ru: "Ваниджа", en: "Vanija", he: "ואניג'ה" },
        { ru: "Вишти (Бхадра)", en: "Vishti (Bhadra)", he: "וישטי (בהדרה)" },
        { ru: "Шакуни", en: "Shakuni", he: "שקוני" },
        { ru: "Чатушпада", en: "Chatushpada", he: "צ'טושפדה" },
        { ru: "Нага", en: "Naga", he: "נאגה" },
        { ru: "Кимстугхна", en: "Kimstughna", he: "קימסטוגהנה" }
    ],
    varas: [
        { id: 0, name: { ru: "Равивар", en: "Ravivar", he: "רביבאר" }, planet: { ru: "Солнце", en: "Sun", he: "שמש" }, day: { ru: "Воскресенье", en: "Sunday", he: "יום ראשון" } },
        { id: 1, name: { ru: "Сомвар", en: "Somvar", he: "סומבאר" }, planet: { ru: "Луна", en: "Moon", he: "ירח" }, day: { ru: "Понедельник", en: "Monday", he: "יום שני" } },
        { id: 2, name: { ru: "Мангалвар", en: "Mangalvar", he: "מנגלבר" }, planet: { ru: "Марс", en: "Mars", he: "מאדים" }, day: { ru: "Вторник", en: "Tuesday", he: "יום שלישי" } },
        { id: 3, name: { ru: "Будхвар", en: "Budhvar", he: "בודוואר" }, planet: { ru: "Меркурий", en: "Mercury", he: "חמה" }, day: { ru: "Среда", en: "Wednesday", he: "יום רביעי" } },
        { id: 4, name: { ru: "Гурувар", en: "Guruvar", he: "גורובר" }, planet: { ru: "Юпитер", en: "Jupiter", he: "צדק" }, day: { ru: "Четверг", en: "Thursday", he: "יום חמישי" } },
        { id: 5, name: { ru: "Шукравар", en: "Shukravar", he: "שוקרבר" }, planet: { ru: "Венера", en: "Venus", he: "נוגה" }, day: { ru: "Пятница", en: "Friday", he: "יום שישי" } },
        { id: 6, name: { ru: "Шанивар", en: "Shanivar", he: "שניבאר" }, planet: { ru: "Сатурн", en: "Saturn", he: "שבתאי" }, day: { ru: "Суббота", en: "Saturday", he: "יום שבת" } }
    ]
};


