
export const MAYAN_DATA = {
    seals: [
        { name: { ru: "Дракон", en: "Dragon", he: "דרקון" }, mayanName: "Imix", action: { ru: "Питает", en: "Nurtures", he: "מזין" }, power: { ru: "Рождение", en: "Birth", he: "לידה" }, essence: { ru: "Бытие", en: "Being", he: "הוויה" } },
        { name: { ru: "Ветер", en: "Wind", he: "רוח" }, mayanName: "Ik", action: { ru: "Сообщает", en: "Communicates", he: "מתקשר" }, power: { ru: "Дух", en: "Spirit", he: "רוח" }, essence: { ru: "Дыхание", en: "Breath", he: "נשימה" } },
        { name: { ru: "Ночь", en: "Night", he: "לילה" }, mayanName: "Akbal", action: { ru: "Мечтает", en: "Dreams", he: "חולם" }, power: { ru: "Изобилие", en: "Abundance", he: "שפע" }, essence: { ru: "Интуиция", en: "Intuition", he: "אינטואיציה" } },
        { name: { ru: "Семя", en: "Seed", he: "זרע" }, mayanName: "Kan", action: { ru: "Нацеливает", en: "Targets", he: "מכוון" }, power: { ru: "Цветение", en: "Flowering", he: "פריחה" }, essence: { ru: "Осознанность", en: "Awareness", he: "מודעות" } },
        { name: { ru: "Змей", en: "Serpent", he: "נחש" }, mayanName: "Chicchan", action: { ru: "Выживает", en: "Survives", he: "שורד" }, power: { ru: "Жизненная сила", en: "Life Force", he: "כוח חיים" }, essence: { ru: "Инстинкт", en: "Instinct", he: "אינסטינקט" } },
        { name: { ru: "Соединитель Миров", en: "Worldbridger", he: "מגשר עולמות" }, mayanName: "Cimi", action: { ru: "Уравнивает", en: "Equalizes", he: "מאזן" }, power: { ru: "Смерть", en: "Death", he: "מוות" }, essence: { ru: "Возможность", en: "Opportunity", he: "הזדמנות" } },
        { name: { ru: "Рука", en: "Hand", he: "יד" }, mayanName: "Manik", action: { ru: "Узнает", en: "Knows", he: "יודע" }, power: { ru: "Свершение", en: "Accomplishment", he: "הישג" }, essence: { ru: "Исцеление", en: "Healing", he: "ריפוי" } },
        { name: { ru: "Звезда", en: "Star", he: "כוכב" }, mayanName: "Lamat", action: { ru: "Украшает", en: "Beautifies", he: "מייפה" }, power: { ru: "Изящество", en: "Elegance", he: "אלגנטיות" }, essence: { ru: "Искусство", en: "Art", he: "אומנות" } },
        { name: { ru: "Луна", en: "Moon", he: "ירח" }, mayanName: "Muluc", action: { ru: "Очищает", en: "Purifies", he: "מטהר" }, power: { ru: "Вода", en: "Water", he: "מים" }, essence: { ru: "Поток", en: "Flow", he: "זרימה" } },
        { name: { ru: "Собака", en: "Dog", he: "כלב" }, mayanName: "Oc", action: { ru: "Любит", en: "Loves", he: "אוהב" }, power: { ru: "Сердце", en: "Heart", he: "לב" }, essence: { ru: "Преданность", en: "Loyalty", he: "נאמנות" } },
        { name: { ru: "Обезьяна", en: "Monkey", he: "קוף" }, mayanName: "Chuen", action: { ru: "Играет", en: "Plays", he: "משחק" }, power: { ru: "Магия", en: "Magic", he: "קסם" }, essence: { ru: "Иллюзия", en: "Illusion", he: "אשליה" } },
        { name: { ru: "Человек", en: "Human", he: "אדם" }, mayanName: "Eb", action: { ru: "Влияет", en: "Influences", he: "משפיע" }, power: { ru: "Свободная воля", en: "Free Will", he: "רצון חופשי" }, essence: { ru: "Мудрость", en: "Wisdom", he: "חוכמה" } },
        { name: { ru: "Странник", en: "Skywalker", he: "הלך שמיים" }, mayanName: "Ben", action: { ru: "Исследует", en: "Explores", he: "חוקר" }, power: { ru: "Пространство", en: "Space", he: "מרחב" }, essence: { ru: "Пробужденность", en: "Wakefulness", he: "ערות" } },
        { name: { ru: "Волшебник", en: "Wizard", he: "קוסם" }, mayanName: "Ix", action: { ru: "Очаровывает", en: "Enchants", he: "מקסים" }, power: { ru: "Вневременность", en: "Timelessness", he: "אל-זמניות" }, essence: { ru: "Восприимчивость", en: "Receptivity", he: "קבלה" } },
        { name: { ru: "Орел", en: "Eagle", he: "עיט" }, mayanName: "Men", action: { ru: "Творит", en: "Creates", he: "יוצר" }, power: { ru: "Видение", en: "Vision", he: "חזון" }, essence: { ru: "Разум", en: "Mind", he: "תבונה" } },
        { name: { ru: "Воин", en: "Warrior", he: "לוחם" }, mayanName: "Cib", action: { ru: "Вопрошает", en: "Questions", he: "שואל" }, power: { ru: "Интеллект", en: "Intelligence", he: "אינטליגנציה" }, essence: { ru: "Бесстрашие", en: "Fearlessness", he: "חוסר פחד" } },
        { name: { ru: "Земля", en: "Earth", he: "אדמה" }, mayanName: "Caban", action: { ru: "Эволюционирует", en: "Evolves", he: "מתפתח" }, power: { ru: "Навигация", en: "Navigation", he: "ניווט" }, essence: { ru: "Синхронность", en: "Synchronicity", he: "סינכרוניות" } },
        { name: { ru: "Зеркало", en: "Mirror", he: "מראה" }, mayanName: "Etznab", action: { ru: "Отражает", en: "Reflects", he: "משקף" }, power: { ru: "Бесконечность", en: "Endlessness", he: "אינסוף" }, essence: { ru: "Порядок", en: "Order", he: "סדר" } },
        { name: { ru: "Буря", en: "Storm", he: "סופה" }, mayanName: "Cauac", action: { ru: "Ускоряет", en: "Catalyzes", he: "מזרז" }, power: { ru: "Самопорождение", en: "Self-Generation", he: "יצירה עצמית" }, essence: { ru: "Энергия", en: "Energy", he: "אנרגיה" } },
        { name: { ru: "Солнце", en: "Sun", he: "שמש" }, mayanName: "Ahau", action: { ru: "Просветляет", en: "Enlightens", he: "מאיר" }, power: { ru: "Вселенский огонь", en: "Universal Fire", he: "אש אוניברסלית" }, essence: { ru: "Жизнь", en: "Life", he: "חיים" } }
    ],
    tones: [
        { name: { ru: "Магнитный", en: "Magnetic", he: "מגנטי" }, mayanName: "Hun", action: { ru: "Привлечение", en: "Attracting", he: "משיכה" }, power: { ru: "Единство", en: "Unity", he: "אחדות" }, essence: { ru: "Цель", en: "Purpose", he: "מטרה" }, question: { ru: "Какова моя цель?", en: "What is my purpose?", he: "מהי המטרה שלי?" } },
        { name: { ru: "Лунный", en: "Lunar", he: "ירחי" }, mayanName: "Ca", action: { ru: "Стабилизация", en: "Stabilizing", he: "ייצוב" }, power: { ru: "Полярность", en: "Polarity", he: "קוטביות" }, essence: { ru: "Вызов", en: "Challenge", he: "אתגר" }, question: { ru: "В чем мой вызов?", en: "What is my challenge?", he: "מהו האתגר שלי?" } },
        { name: { ru: "Электрический", en: "Electric", he: "חשמלי" }, mayanName: "Ox", action: { ru: "Активация", en: "Activating", he: "הפעלה" }, power: { ru: "Служение", en: "Service", he: "שירות" }, essence: { ru: "Связь", en: "Bonding", he: "חיבור" }, question: { ru: "Как я могу лучше всего служить?", en: "How can I best serve?", he: "איך אני יכול לשרת בצורה הטובה ביותר?" } },
        { name: { ru: "Самосущный", en: "Self-Existing", he: "קיים מעצמו" }, mayanName: "Can", action: { ru: "Определение", en: "Defining", he: "הגדרה" }, power: { ru: "Форма", en: "Form", he: "צורה" }, essence: { ru: "Мера", en: "Measure", he: "מדידה" }, question: { ru: "Какова форма действия?", en: "What is the form of action?", he: "מהי צורת הפעולה?" } },
        { name: { ru: "Обертонный", en: "Overtone", he: "אוברטון" }, mayanName: "Ho", action: { ru: "Наделение силой", en: "Empowering", he: "העצמה" }, power: { ru: "Сияние", en: "Radiance", he: "זוהר" }, essence: { ru: "Управление", en: "Command", he: "פיקוד" }, question: { ru: "Как я могу наделиться силой?", en: "How can I empower myself?", he: "איך אני יכול להעצים את עצמי?" } },
        { name: { ru: "Ритмический", en: "Rhythmic", he: "קצבי" }, mayanName: "Uac", action: { ru: "Организация", en: "Organizing", he: "ארגון" }, power: { ru: "Равенство", en: "Equality", he: "שוויון" }, essence: { ru: "Баланс", en: "Balance", he: "איזון" }, question: { ru: "Как мне организовать себя для равенства?", en: "How can I organize for equality?", he: "איך אני יכול להתארגן לשוויון?" } },
        { name: { ru: "Резонансный", en: "Resonant", he: "מהדהד" }, mayanName: "Uuk", action: { ru: "Вдохновение", en: "Inspiring", he: "השראה" }, power: { ru: "Канал", en: "Channel", he: "ערוץ" }, essence: { ru: "Сонастройка", en: "Attunement", he: "כוונון" }, question: { ru: "Как сонастроить мне себя в служении другим?", en: "How can I attune my service to others?", he: "איך אני יכול לכוונן את השירות שלי לאחרים?" } },
        { name: { ru: "Галактический", en: "Galactic", he: "גלקטי" }, mayanName: "Vaxac", action: { ru: "Моделирование", en: "Modeling", he: "מודלים" }, power: { ru: "Целостность", en: "Integrity", he: "יושרה" }, essence: { ru: "Гармония", en: "Harmony", he: "הרמוניה" }, question: { ru: "Живу ли я тем, во что верю?", en: "Do I live what I believe?", he: "האם אני חי את מה שאני מאמין בו?" } },
        { name: { ru: "Солнечный", en: "Solar", he: "סולארי" }, mayanName: "Bolon", action: { ru: "Реализация", en: "Realizing", he: "מימוש" }, power: { ru: "Намерение", en: "Intention", he: "כוונה" }, essence: { ru: "Пульсация", en: "Pulsation", he: "פעימה" }, question: { ru: "Как мне достичь цели?", en: "How do I attain my purpose?", he: "איך אני משיג את המטרה שלי?" } },
        { name: { ru: "Планетарный", en: "Planetary", he: "פלנטרי" }, mayanName: "Lahun", action: { ru: "Производство", en: "Producing", he: "ייצור" }, power: { ru: "Проявленность", en: "Manifestation", he: "התגלמות" }, essence: { ru: "Совершенствование", en: "Perfection", he: "שלמות" }, question: { ru: "Как мне улучшить то, что я делаю?", en: "How do I perfect what I do?", he: "איך אני משפר את מה שאני עושה?" } },
        { name: { ru: "Спектральный", en: "Spectral", he: "ספקטרלי" }, mayanName: "Buluk", action: { ru: "Высвобождение", en: "Releasing", he: "שחרור" }, power: { ru: "Растворение", en: "Dissolution", he: "פירוק" }, essence: { ru: "Освобождение", en: "Liberation", he: "חופש" }, question: { ru: "Как мне освободиться и отпустить?", en: "How do I release and let go?", he: "איך אני משחרר ומרפה?" } },
        { name: { ru: "Кристаллический", en: "Crystal", he: "קריסטלי" }, mayanName: "Lahac", action: { ru: "Сотрудничество", en: "Cooperation", he: "שיתוף פעולה" }, power: { ru: "Посвящение", en: "Dedication", he: "הקדשה" }, essence: { ru: "Универсализация", en: "Universalization", he: "אוניברסליזציה" }, question: { ru: "Как мне посвятить себя всему живому?", en: "How can I dedicate myself to all that lives?", he: "איך אני יכול להקדיש את עצמי לכל החי?" } },
        { name: { ru: "Космический", en: "Cosmic", he: "קוסמי" }, mayanName: "Oxlahun", action: { ru: "Присутствие", en: "Presence", he: "נוכחות" }, power: { ru: "Стойкость", en: "Endurance", he: "סיבולת" }, essence: { ru: "Трансцендентность", en: "Transcendence", he: "התעלות" }, question: { ru: "Как мне расширить свою радость и любовь?", en: "How can I expand my joy and love?", he: "איך אני יכול להרחיב את השמחה והאהבה שלי?" } }
    ],
    moons: [
        { name: { ru: "Магнитная Луна Цели", en: "Magnetic Moon of Purpose", he: "ירח מגנטי של מטרה" }, question: { ru: "Какова моя цель?", en: "What is my purpose?", he: "מהי המטרה שלי?" } },
        { name: { ru: "Лунная Луна Вызова", en: "Lunar Moon of Challenge", he: "ירח ירחי של אתגר" }, question: { ru: "В чем мой вызов?", en: "What is my challenge?", he: "מהו האתגר שלי?" } },
        { name: { ru: "Электрическая Луна Служения", en: "Electric Moon of Service", he: "ירח חשמלי של שירות" }, question: { ru: "Как я могу лучше всего служить?", en: "How can I best serve?", he: "איך אני יכול לשרת?" } },
        { name: { ru: "Самосущная Луна Формы", en: "Self-Existing Moon of Form", he: "ירח קיים מעצמו של צורה" }, question: { ru: "Какова форма действия?", en: "What is the form of action?", he: "מהי צורת הפעולה?" } },
        { name: { ru: "Обертонная Луна Сияния", en: "Overtone Moon of Radiance", he: "ירח אוברטון של זוהר" }, question: { ru: "Как я могу наделиться силой?", en: "How can I empower myself?", he: "איך אני יכול להעצים את עצמי?" } },
        { name: { ru: "Ритмическая Луна Равенства", en: "Rhythmic Moon of Equality", he: "ירח קצבי של שוויון" }, question: { ru: "Как мне организовать себя для равенства?", en: "How can I organize for equality?", he: "איך אני יכול להתארגן לשוויון?" } },
        { name: { ru: "Резонансная Луна Сонастройки", en: "Resonant Moon of Attunement", he: "ירח מהדהד של כוונון" }, question: { ru: "Как сонастроить мне себя в служении другим?", en: "How can I attune my service to others?", he: "איך אני יכול לכוונן את השירות שלי?" } },
        { name: { ru: "Галактическая Луна Целостности", en: "Galactic Moon of Integrity", he: "ירח גלקטי של יושרה" }, question: { ru: "Живу ли я тем, во что верю?", en: "Do I live what I believe?", he: "האם אני חי את אמונתי?" } },
        { name: { ru: "Солнечная Луна Намерения", en: "Solar Moon of Intention", he: "ירח סולארי של כוונה" }, question: { ru: "Как мне достичь цели?", en: "How do I attain my purpose?", he: "איך אני משיג את המטרה?" } },
        { name: { ru: "Планетарная Луна Проявленности", en: "Planetary Moon of Manifestation", he: "ירח פלנטרי של התגלמות" }, question: { ru: "Как мне улучшить то, что я делаю?", en: "How do I perfect what I do?", he: "איך אני משפר את מעשיי?" } },
        { name: { ru: "Спектральная Луна Освобождения", en: "Spectral Moon of Liberation", he: "ירח ספקטרלי של שחרור" }, question: { ru: "Как мне освободиться и отпустить?", en: "How do I release and let go?", he: "איך אני משחרר?" } },
        { name: { ru: "Кристаллическая Луна Сотрудничества", en: "Crystal Moon of Cooperation", he: "ירח קריסטלי של שיתוף פעולה" }, question: { ru: "Как мне посвятить себя всему живому?", en: "How can I dedicate myself to all that lives?", he: "איך אני מקדיש עצמי לחיים?" } },
        { name: { ru: "Космическая Луна Присутствия", en: "Cosmic Moon of Presence", he: "ירח קוסמי של נוכחות" }, question: { ru: "Как мне расширить свою радость и любовь?", en: "How can I expand my joy and love?", he: "איך אני מרחיב שמחה ואהבה?" } }
    ],
    totems: {
        ru: ["Летучая Мышь", "Скорпион", "Олень", "Сова", "Павлин", "Ящерица", "Обезьяна", "Ястреб", "Ягуар", "Собака", "Змея", "Кролик", "Черепаха"],
        en: ["Bat", "Scorpio", "Deer", "Owl", "Peacock", "Lizard", "Monkey", "Hawk", "Jaguar", "Dog", "Serpent", "Rabbit", "Turtle"],
        he: ["עטלף", "עקרב", "צבי", "ינשוף", "טווס", "לטאה", "קוף", "נץ", "יגואר", "כלב", "נחש", "ארנב", "צב"]
    }
};


